/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ConsoleCurrencyCalc;

import ConsoleCurrencyCalc.calculator.CurrencyCalc;
import ConsoleCurrencyCalc.parsers.DollarParser;
import ConsoleCurrencyCalc.parsers.RubleParser;
import lombok.RequiredArgsConstructor;

import java.io.*;
import java.util.Scanner;

@RequiredArgsConstructor
public class App {
    private final InputStream inputStream;
    private final OutputStream outputStream;
    private final CurrencyCalc calc;

    public void run() throws IOException {
        try(var scanner = new Scanner(inputStream)) {
            try (var writer = new OutputStreamWriter(outputStream)) {
                String line = null;
                while (scanner.hasNextLine() && !(line = scanner.nextLine()).equals("")) {
                    var res = calc.calculate(line);
                    writer.write(String.format("%s = %s\n", line, res.toString()));
                    writer.flush();
                }
            }
        }
    }

    public static void main(String[] args) {
        try {
            var calc = CurrencyCalc
                    .builder()
                    .parser(new DollarParser())
                    .parser(new RubleParser())
                    .build();
            new App(System.in, System.out, calc).run();
        }
        catch (Exception e) {
            System.out.println("Exception error.");
            System.out.println(e.getMessage());
        }
    }
}
